apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/melderan/cnpg-i-scale-to-zero
  newName: cnpg-i-scale-to-zero-plugin
  newTag: dev
secretGenerator:
- literals:
  - SIDECAR_IMAGE=cnpg-scale-to-zero-sidecar:dev
  name: scale-to-zero-config
  behavior: replace
patches:
- target:
    kind: Deployment
    name: scale-to-zero
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: debug
